### ISSUE TITLE
Add units for system-defined inputs

### ISSUE THREAD

**Issue by cllde8** [LabIMotion/labimotion#25]
The issue was reported at https://github.com/ComPlat/chemotion_ELN/issues/1453.

Continue the discussion

> [µm] for Length ... is not available according to the list!

--- by [martin-held-hereon](https://github.com/martin-held-hereon)

**Comment by cllde8** [comment]
Dear @martin-held-hereon,

The system now offers options for both [Length](https://github.com/LabIMotion/labimotion/wiki/Supported-Units-for-System-Defined-Field#length) and [Subatomic length](https://github.com/LabIMotion/labimotion/wiki/Supported-Units-for-System-Defined-Field#subatomic-length), aimed at enhancing user experience. This strategic division ensures that users have access to the most relevant units for their varied applications.

We value your feedback and thoughts. If you have any questions or suggestions, please don't hesitate to share them with us. Kindly refer to this link [[I cannot find the specific units I need, what should I do?](https://github.com/LabIMotion/labimotion/wiki/Supported-Units-for-System-Defined-Field#-i-cannot-find-the-specific-units-i-need-what-should-i-do)] for more information.

Thank you.

Best regards,
Claire

**Comment by martin-held-hereon** [comment]
@cllde8 
Thanks for the clarification!
