### ISSUE TITLE
upload of dx files to analyses sections does not work 

### ISSUE THREAD

**Issue by nicolejung** [LabIMotion/labimotion#35]
I tried to upload a *.dx (NMR from chemotion repo) into an analysis within a workflow element and the system crashes with this challenge. The upload bar is shown but does not disappear anymore and the page has to be reloaded

**Comment by phuang26** [comment]
Hi Nicole,

The maximum upload file size was previously limited to 1MB, but the file you uploaded was 1.1 MB, so it couldn't be uploaded. I've updated the settings to allow files up to 50MB, so it should work now.
