### ISSUE TITLE
Faulty assignment of Generic Segment provided by LabIMotion Hub??

### ISSUE THREAD

**Issue by cllde8** [LabIMotion/labimotion#7]
The issue was reported at https://github.com/ComPlat/chemotion_ELN/issues/1751

**Comment by cllde8** [comment]
Hi @FabianFink and @MichaelOCI

Could you please provide your ELN version? Thank you very much.

Best regards,
Claire

**Comment by FabianFink** [comment]
Hi Claire,
I tried fetching segments from the LabIMotion Hub on two different instances both running on version 1.8.2, one instance hosted here at our site in Aachen, one hosted by the KIT for our Chemotion workshops.

**Comment by MichaelOCI** [comment]
Hello,
regarding your request for the ELN Version(s) by mail. The 1st VM was installed 17.1.2024 with Chemotion ELN 1.8.1
the 2nd VM is from 12.2.2024 with Chemotion ELN 1.8.2
Best regards
Michael

Dr. Michael Nöthe 

Technische Universität Dresden
Fakultät Chemie und Lebensmittelchemie
Professur für Organische Chemie I
01062 Dresden 

Tel.: +49 (351) 463 36197

Web: https://tu-dresden.de/mn/chemie/oc/oc1/die-professur/mitarbeiter2022/dr-michael-noethe

**Comment by cllde8** [comment]
Hi @FabianFink and @MichaelOCI

Thanks a lot for the information. I will keep you posted.

Best regards,
Claire

**Comment by cllde8** [comment]
Hi @FabianFink and @MichaelOCI 

The issue has been resolved. Could you please take a moment to try it out by synchronizing the template and share your feedback with us? Thank you very much.

Best regards,
Claire

**Comment by FabianFink** [comment]
Hey Claire,
It now works at our instances as expected as well. Thank you very much!
Best,
Fabian

**Comment by cllde8** [comment]
Hi @FabianFink 

Thank you for the prompt feedback. I will now close this ticket. Please feel free to reach out if you encounter any [issues](https://github.com/LabIMotion/labimotion/issues) or have [suggestions](https://github.com/LabIMotion/labimotion/discussions).

Best regards,
Claire
